# Generated by Django 3.2 on 2021-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
