# Generated by Django 3.2 on 2021-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fapp/'),
        ),
    ]
