# Generated by Django 3.2.3 on 2021-05-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicapp',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
